project:
  type: website
  output-dir: docs

website:
  title: "sona kalanlaR"
  navbar:
    search: true
    left:
      - text: Ana Sayfa
        href: index.qmd
      - text: Takım Üyeleri
        href: takim.qmd
      - text: Proje
        href: proje.qmd
    right:
      - text: Porfolyo
        href: portfolyo.qmd



            
    tools:
      - icon: github
        href: https://github.com

  sidebar:
    - title: "Ana Sayfa"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        
    - title: "Takım Üyeleri"
      style: "docked"
      search: true
      contents:
        - takim.qmd
        - takim/muhammeddogan.qmd
        - takim/tulayaras.qmd  
        - takim/sudesengul.qmd  
        - takim/eceakbulut.qmd  
        
        
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "MUY665 - 2025 Bahar" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual